In [1]:
import pandas as pd

df = pd.read_csv("../data/mbti_1.csv")
df.head()

   type                                              posts
0  INFJ  'http://www.youtube.com/watch?v=qsXHcwe3krw|||...
1  ENTP  'I'm finding the lack of me in these posts ver...
2  INTP  'Good one  _____   https://www.youtube.com/wat...
3  INTJ  'Dear INTP,   I enjoyed our conversation the o...
4  ENTJ  'You're fired.|||That's another silly misconce...

In [2]:
df.shape

(8675, 2)

In [3]:
df.columns

Index(['type', 'posts'], dtype='str')

In [4]:
df['type'].unique()

<StringArray>
['INFJ', 'ENTP', 'INTP', 'INTJ', 'ENTJ', 'ENFJ', 'INFP', 'ENFP', 'ISFP',
 'ISTP', 'ISFJ', 'ISTJ', 'ESTP', 'ESFP', 'ESTJ', 'ESFJ']
Length: 16, dtype: str

In [5]:
df['type'].value_counts()

type
INFP    1832
INFJ    1470
INTP    1304
INTJ    1091
ENTP     685
ENFP     675
ISTP     337
ISFP     271
ENTJ     231
ISTJ     205
ENFJ     190
ISFJ     166
ESTP      89
ESFP      48
ESFJ      42
ESTJ      39
Name: count, dtype: int64

In [6]:
import re

In [7]:
def clean_text(text):
    # remove URLs
    text = re.sub(r'http\S+', '', text)
    
    # remove special characters
    text = re.sub(r'[^A-Za-z\s]', '', text)
    
    # convert to lowercase
    text = text.lower()
    
    return text

In [8]:
df['cleaned_posts'] = df['posts'].apply(clean_text)

In [9]:
df[['posts', 'cleaned_posts']].head()

,posts,cleaned_posts
0,'http://www.youtube.com/watch?v=qsXHcwe3krw|||...,and intj moments sportscenter not top ten ...
1,'I'm finding the lack of me in these posts ver...,im finding the lack of me in these posts very ...
2,'Good one _____ https://www.youtube.com/wat...,good one course to which i say i know tha...
3,"'Dear INTP, I enjoyed our conversation the o...",dear intp i enjoyed our conversation the oth...
4,'You're fired.|||That's another silly misconce...,youre firedthats another silly misconception t...